name: PHPUnit

on: [push, pull_request]

jobs:
  laravel6:
    name: Laravel 6.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^6.0
      php: '["8.0"]'
      doctrine: ^2.6
  laravel7:
    name: Laravel 7.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^7.0
      php: '["8.0"]'
      doctrine: ^2.6
  laravel8:
    name: Laravel 8.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^8.79
      php: '["8.0", "8.1"]'
      doctrine: ^3.5
  laravel9:
    name: Laravel 9.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^9.0
      php: '["8.0", "8.1"]'
      doctrine: ^3.5
  laravel10:
    name: Laravel 10.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^10.0
      php: '["8.1", "8.5"]'
      doctrine: ^3.5
  laravel11:
    name: Laravel 11.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^11.0
      php: '["8.2", "8.5"]'
  laravel12:
    name: Laravel 12.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^12.0
      php: '["8.2", "8.5"]'
  laravel13:
    name: Laravel 13.x
    uses: ./.github/workflows/phpunit-laravel.yml
    with:
      laravel: ^13.0
      php: '["8.3", "8.5"]'
