name: PHPUnit (Laravel)

on:
  workflow_call:
    inputs:
      doctrine:
        required: false
        type: string
      laravel:
        required: true
        type: string
      php:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJSON(inputs.php) }}
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    services:
      postgres:
        image: timescale/timescaledb-ha:pg18
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ inputs.laravel }}" "doctrine/dbal:${{ inputs.doctrine || '*' }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --no-security-blocking --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_HOST: localhost
          DB_DATABASE: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
